#!/bin/bash
if [ $# -ne 1 ]; then # checks if the input is there
    echo "Usage: $0 <4-digit-integer>"
    exit 1
fi
echo -n "$1" | sha256sum | awk '{print $1}' #gives number to hash function and then it prints it

